/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationIndexRouteImport } from './routes/location/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as LocationLocationIdIndexRouteImport } from './routes/location/$locationId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdIndexRoute = LocationLocationIdIndexRouteImport.update({
  id: '/location/$locationId/',
  path: '/location/$locationId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartIndexRoute
  '/location': typeof LocationIndexRoute
  '/location/$locationId': typeof LocationLocationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartIndexRoute
  '/location': typeof LocationIndexRoute
  '/location/$locationId': typeof LocationLocationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart/': typeof CartIndexRoute
  '/location/': typeof LocationIndexRoute
  '/location/$locationId/': typeof LocationLocationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart' | '/location' | '/location/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/location' | '/location/$locationId'
  id: '__root__' | '/' | '/cart/' | '/location/' | '/location/$locationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartIndexRoute: typeof CartIndexRoute
  LocationIndexRoute: typeof LocationIndexRoute
  LocationLocationIdIndexRoute: typeof LocationLocationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId/': {
      id: '/location/$locationId/'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartIndexRoute: CartIndexRoute,
  LocationIndexRoute: LocationIndexRoute,
  LocationLocationIdIndexRoute: LocationLocationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
